import Head from 'next/head';
import TopArtist from "../components/creators/TopArtist";
import Hero1 from '../components/hero/Hero1';
import HeroPreview from '../components/hero/HeroPreview';
import styles from '../styles/Home.module.css';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero1 />
        <HeroPreview />
        <TopArtist />
      </div>
    </div>
  )
}